apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app }}
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Values.app }}
              image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              env:
                - name: APP_VERSION
                  value: {{ .Chart.AppVersion | quote }}
